import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, Clock3, FileText, Mail, MapPin, Package, Phone, Truck, User } from 'lucide-react';
import Loading from '../../components/Loading.tsx';
import ImageWithSkeleton from '../../components/ImageWithSkeleton.tsx';
import { ordersApi } from '../../services/api.ts';
const labels={pending:'En attente',confirmed:'Confirmée',preparing:'Préparation',shipped:'Expédiée',delivered:'Livrée',cancelled:'Annulée'};
export default function AdminOrderDetails(){const{id}=useParams(),[order,setOrder]=useState(null),[loading,setLoading]=useState(true);useEffect(()=>{ordersApi.one(id).then(setOrder).finally(()=>setLoading(false))},[id]);if(loading)return <Loading/>;if(!order)return <p>Commande introuvable.</p>;return <>
 <div className="admin-title"><div><Link className="back-link" to="/admin/orders"><ArrowLeft size={16}/>Retour</Link><h1>Commande {order.orderNumber}</h1><p>{new Date(order.createdAt).toLocaleString('fr-FR')}</p></div><span className={`status-badge ${order.status}`}>{labels[order.status]}</span></div>
 <div className="order-detail-grid"><section className="admin-panel"><h2><User size={18}/>Client</h2><div className="detail-lines"><p><b>{order.customer.fullName}</b></p><p><Mail size={16}/>{order.customer.email}</p><p><Phone size={16}/>{order.customer.phone}</p><p><MapPin size={16}/>{order.customer.address}, {order.customer.city} {order.customer.postalCode}<br/>{order.customer.governorate ? `${order.customer.governorate}, ` : ''}{order.customer.country || 'Tunisie'}</p>{order.user ? <p>Compte associé : <b>{order.user.name}</b> ({order.user.email})</p> : <p>Commande sans compte client</p>}</div></section><section className="admin-panel"><h2><Truck size={18}/>Livraison & paiement</h2><div className="detail-lines"><p>{order.delivery?.label || 'Livraison à domicile'}</p><p>Frais : <b>{Number(order.delivery?.fee ?? order.deliveryFee ?? 0).toFixed(2)} DT</b></p><p>Paiement : {order.paymentMethod === 'cash_on_delivery' ? 'à la livraison' : order.paymentMethod}</p><p>Email admin : {order.adminEmailSent?'envoyé':order.adminEmailError?`erreur — ${order.adminEmailError}`:'non envoyé'}</p><p>Stock : {order.stockRestored ? 'remis en stock' : 'réservé pour la commande'}</p></div></section></div>
 {order.note ? <section className="admin-panel order-note"><h2><FileText size={18}/>Note du client</h2><p>{order.note}</p></section> : null}
 <section className="admin-panel"><h2><Package size={18}/>Produits commandés</h2><div className="admin-table-wrap"><table><thead><tr><th>Produit</th><th>Catégorie / sous-catégorie</th><th>Qté</th><th>Prix</th><th>Total</th></tr></thead><tbody>{order.items.map((item,i)=>{const cats=item.product?.categories||item.categories||[];return <tr key={i}><td><div className="order-product-cell"><ImageWithSkeleton wrapperClassName="order-product-image" src={item.image||item.product?.images?.[0]} alt=""/><span><b>{item.name}</b><small>{item.product?.sku||''}</small></span></div></td><td>{cats.map(c=><span className="category-tag" key={c._id||c.slug}>{c.parent?.name?`${c.parent.name} › `:''}{c.name}</span>)}</td><td>{item.quantity}</td><td>{Number(item.price).toFixed(2)} DT</td><td><b>{(item.price*item.quantity).toFixed(2)} DT</b></td></tr>})}</tbody></table></div></section>
 <div className="order-detail-grid"><section className="admin-panel"><h2><Clock3 size={18}/>Historique du statut</h2><div className="admin-order-timeline">{(order.statusHistory?.length ? order.statusHistory : [{status:order.status,changedAt:order.createdAt}]).map((entry,index)=><div key={`${entry.status}-${index}`}><i></i><span><b>{labels[entry.status]||entry.status}</b><small>{new Date(entry.changedAt).toLocaleString('fr-FR')}{entry.changedBy?.name?` • ${entry.changedBy.name}`:''}</small>{entry.note?<p>{entry.note}</p>:null}</span></div>)}</div></section><section className="order-total-card"><p><span>Sous-total</span><b>{Number(order.subtotal).toFixed(2)} DT</b></p><p><span>Livraison</span><b>{Number(order.delivery?.fee ?? order.deliveryFee ?? 0).toFixed(2)} DT</b></p><p className="grand"><span>Total</span><b>{Number(order.total).toFixed(2)} DT</b></p></section></div>
 </>}
